services:
  metabase:
    image: metabase/metabase:v0.50.24
    container_name: metabase4my_geonode
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      MB_EMBEDDING_SECRET_KEY: ${METABASE_SECRET_KEY}
      MB_SITE_URL: http://192.168.2.119/metabase
      JAVA_TOOL_OPTIONS: "-Xmx768m -Xms256m"
    volumes:
      - metabase_data:/metabase-data
    networks:
      - my_geonode_default
    restart: unless-stopped

volumes:
  metabase_data:

networks:
  my_geonode_default:
    external: true
