# Generated by Django 3.2.20 on 2026-06-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Anonymous', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('category', models.CharField(choices=[('data_request', 'Data Request'), ('general', 'General Feedback'), ('map_issue', 'Map Issue'), ('bug_report', 'Bug Report')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Internal notes about this feedback and actions taken')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
